/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOA
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupData = new javax.swing.ButtonGroup();
        btnGroupQuery = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radio100 = new javax.swing.JRadioButton();
        radio5k = new javax.swing.JRadioButton();
        radio60k = new javax.swing.JRadioButton();
        radio1M = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        radioBasic = new javax.swing.JRadioButton();
        radioAdvance = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        queryCombobox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnQuery = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbTime = new javax.swing.JLabel();
        tableQuery = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tập dữ liệu"));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        btnGroupData.add(radio100);
        radio100.setSelected(true);
        radio100.setText("100 - 200");
        radio100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio100ActionPerformed(evt);
            }
        });
        jPanel2.add(radio100);

        btnGroupData.add(radio5k);
        radio5k.setText("5000 - 7000");
        radio5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5kActionPerformed(evt);
            }
        });
        jPanel2.add(radio5k);

        btnGroupData.add(radio60k);
        radio60k.setText("60k - 80k");
        radio60k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio60kActionPerformed(evt);
            }
        });
        jPanel2.add(radio60k);

        btnGroupData.add(radio1M);
        radio1M.setText("1M - 2M");
        radio1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1MActionPerformed(evt);
            }
        });
        jPanel2.add(radio1M);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại truy vấn"));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        btnGroupQuery.add(radioBasic);
        radioBasic.setSelected(true);
        radioBasic.setText("Cơ bản");
        radioBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBasicActionPerformed(evt);
            }
        });
        jPanel3.add(radioBasic);

        btnGroupQuery.add(radioAdvance);
        radioAdvance.setText("Nâng cao");
        radioAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdvanceActionPerformed(evt);
            }
        });
        jPanel3.add(radioAdvance);

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn câu truy vấn"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        queryCombobox.setMaximumSize(new java.awt.Dimension(300, 20));
        queryCombobox.setMinimumSize(new java.awt.Dimension(300, 20));
        queryCombobox.setPreferredSize(new java.awt.Dimension(300, 20));
        queryCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryComboboxActionPerformed(evt);
            }
        });
        jPanel4.add(queryCombobox, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        queryTextArea.setColumns(20);
        queryTextArea.setRows(5);
        jScrollPane1.setViewportView(queryTextArea);

        jPanel6.add(jScrollPane1);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel8.setMinimumSize(new java.awt.Dimension(73, 44));
        jPanel8.setName(""); // NOI18N

        btnQuery.setText("Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        jPanel8.add(btnQuery);

        jPanel6.add(jPanel8);

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        lbTime.setText("Thời gian truy vấn:");
        jPanel7.add(lbTime);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableQuery.setViewportView(jTable1);

        jPanel7.add(tableQuery);

        jPanel5.add(jPanel7);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1MActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio1MActionPerformed

    private void queryComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryComboboxActionPerformed
        // TODO add your handling code here:
        comboboxSelection();
    }//GEN-LAST:event_queryComboboxActionPerformed

    private void radio100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio100ActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio100ActionPerformed

    private void radio5kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5kActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio5kActionPerformed

    private void radio60kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio60kActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio60kActionPerformed

    private void radioBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBasicActionPerformed
        // TODO add your handling code here:
        queryTypeSeletion();
    }//GEN-LAST:event_radioBasicActionPerformed

    private void radioAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdvanceActionPerformed
        // TODO add your handling code here:
        queryTypeSeletion();
    }//GEN-LAST:event_radioAdvanceActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        // TODO add your handling code here:
        btnQueryClicked();
    }//GEN-LAST:event_btnQueryActionPerformed

    public void repositorySelection() {
        
    }
    
    public void queryTypeSeletion() {
        
    }
    
    public void comboboxSelection() {
        
    }
    
    public void btnQueryClicked() {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupData;
    private javax.swing.ButtonGroup btnGroupQuery;
    private javax.swing.JButton btnQuery;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTime;
    private javax.swing.JComboBox<String> queryCombobox;
    private javax.swing.JTextArea queryTextArea;
    private javax.swing.JRadioButton radio100;
    private javax.swing.JRadioButton radio1M;
    private javax.swing.JRadioButton radio5k;
    private javax.swing.JRadioButton radio60k;
    private javax.swing.JRadioButton radioAdvance;
    private javax.swing.JRadioButton radioBasic;
    private javax.swing.JScrollPane tableQuery;
    // End of variables declaration//GEN-END:variables
}
