package n06.oop.gui;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import n06.oop.database.ConnectionManager;
import n06.oop.database.Setting;
import n06.oop.query.QueryResult;
import n06.oop.query.QueryUtils;
import org.eclipse.rdf4j.query.QueryEvaluationException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.util.Map;

/**
 *
 * @author HOA
 */
public class GUI extends javax.swing.JFrame {

    private Map.Entry[] basicQueries;
    private Map.Entry[] advanceQueries;

    static final String prefixes = "PREFIX prop: <http://nhom06/property#>\n" +
            "PREFIX rel: <http://nhom06/relationship#>\n" +
            "PREFIX model: <http://nhom06/model#>\n" +
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>";

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        init();
        repositorySelection();
        queryTypeSeletion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupData = new javax.swing.ButtonGroup();
        btnGroupQuery = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radio100 = new javax.swing.JRadioButton();
        radio5k = new javax.swing.JRadioButton();
        radio60k = new javax.swing.JRadioButton();
        radio1M = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        radioBasic = new javax.swing.JRadioButton();
        radioAdvance = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        queryCombobox = new javax.swing.JComboBox<>();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnQuery = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbTime = new javax.swing.JLabel();
        tableQuery = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tập dữ liệu"));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        btnGroupData.add(radio100);
        radio100.setSelected(true);
        radio100.setText("100 - 200");
        radio100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio100ActionPerformed(evt);
            }
        });
        jPanel2.add(radio100);

        btnGroupData.add(radio5k);
        radio5k.setText("5000 - 7000");
        radio5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5kActionPerformed(evt);
            }
        });
        jPanel2.add(radio5k);

        btnGroupData.add(radio60k);
        radio60k.setText("60k - 80k");
        radio60k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio60kActionPerformed(evt);
            }
        });
        jPanel2.add(radio60k);

        btnGroupData.add(radio1M);
        radio1M.setText("1M - 2M");
        radio1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1MActionPerformed(evt);
            }
        });
        jPanel2.add(radio1M);

        btnGroupData.add(jRadioButton2);
        jRadioButton2.setText("15M - 17M");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại truy vấn"));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        btnGroupQuery.add(radioBasic);
        radioBasic.setSelected(true);
        radioBasic.setText("Cơ bản");
        radioBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBasicActionPerformed(evt);
            }
        });
        jPanel3.add(radioBasic);

        btnGroupQuery.add(radioAdvance);
        radioAdvance.setText("Nâng cao");
        radioAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdvanceActionPerformed(evt);
            }
        });
        jPanel3.add(radioAdvance);

        btnGroupQuery.add(jRadioButton1);
        jRadioButton1.setText("Tuỳ chọn");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn câu truy vấn"));
        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 115));
        jPanel4.setMinimumSize(new java.awt.Dimension(512, 115));
        jPanel4.setPreferredSize(new java.awt.Dimension(512, 115));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        queryCombobox.setMaximumSize(new java.awt.Dimension(500, 20));
        queryCombobox.setMinimumSize(new java.awt.Dimension(500, 20));
        queryCombobox.setPreferredSize(new java.awt.Dimension(500, 20));
        queryCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryComboboxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(queryCombobox, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        queryTextArea.setColumns(20);
        queryTextArea.setRows(5);
        jScrollPane1.setViewportView(queryTextArea);

        jPanel6.add(jScrollPane1);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 44));
        jPanel8.setMinimumSize(new java.awt.Dimension(73, 44));
        jPanel8.setName(""); // NOI18N

        btnQuery.setText("Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        jPanel8.add(btnQuery);

        jPanel6.add(jPanel8);

        jSplitPane1.setLeftComponent(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        lbTime.setText("Thời gian truy vấn:");
        jPanel7.add(lbTime);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        tableQuery.setViewportView(jTable1);

        jPanel7.add(tableQuery);

        jSplitPane1.setRightComponent(jPanel7);

        jPanel5.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("File");

        jMenuItem1.setText("Sinh dữ liệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thống kê");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1MActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio1MActionPerformed

    private void queryComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryComboboxActionPerformed
        // TODO add your handling code here:
        comboboxSelection();
    }//GEN-LAST:event_queryComboboxActionPerformed

    private void radio100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio100ActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio100ActionPerformed

    private void radio5kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5kActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio5kActionPerformed

    private void radio60kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio60kActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_radio60kActionPerformed

    private void radioBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBasicActionPerformed
        // TODO add your handling code here:
        queryTypeSeletion();
    }//GEN-LAST:event_radioBasicActionPerformed

    private void radioAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdvanceActionPerformed
        // TODO add your handling code here:
        queryTypeSeletion();
    }//GEN-LAST:event_radioAdvanceActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        // TODO add your handling code here:
        btnQueryClicked();
    }//GEN-LAST:event_btnQueryActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        queryTypeSeletion();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        repositorySelection();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GenerateDialog dialog = new GenerateDialog(this, rootPaneCheckingEnabled);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void repositorySelection() {
        String repositoryId = null;
        if (radio100.isSelected()) {
            repositoryId = Setting.REPO_NAME_100_200;
        } else if (radio5k.isSelected()) {
            repositoryId = Setting.REPO_NAME_5k_7k;
        } else if (radio60k.isSelected()) {
            repositoryId = Setting.REPO_NAME_60k_80k;
        } else if (radio1M.isSelected()) {
            repositoryId = Setting.REPO_NAME_1m_2m;
        } else {
            repositoryId = Setting.REPO_NAME_15m_17m;
        }

        System.out.println(repositoryId);

        ConnectionManager.setRepository(repositoryId);
    }

    public void queryTypeSeletion() {
        queryCombobox.setEnabled(true);
        queryTextArea.setText("");
        if (radioBasic.isSelected()) {
            DefaultComboBoxModel<Map.Entry<String, String>> model = new DefaultComboBoxModel<>(basicQueries);
            queryCombobox.setModel(model);
        } else if (radioAdvance.isSelected()) {
            DefaultComboBoxModel<Map.Entry<String, String>> model = new DefaultComboBoxModel<>(advanceQueries);
            queryCombobox.setModel(model);
        } else {
            queryCombobox.setEnabled(false);
            queryTextArea.setText(prefixes);
        }
        jTable1.setModel(new DefaultTableModel());
    }

    public void comboboxSelection() {
        Map.Entry<String,String> entry = (Map.Entry<String, String>) queryCombobox.getSelectedItem();
        queryTextArea.setText(entry.getValue());
    }

    public void btnQueryClicked() {
        String sql = queryTextArea.getText();
        try {
            QueryResult result = QueryUtils.query(sql);
            TableModel model = new DefaultTableModel(result.getData(), result.getHeader());
            jTable1.setModel(model);
            lbTime.setText("Thời gian truy vấn: " + result.getTimeExec() + " ms");
        } catch (QueryEvaluationException e) {
            String mess = e.getMessage();
            JOptionPane.showMessageDialog(this, mess);
        }

    }


    public void init() {
        Map<String, String> basic = QueryUtils.loadData(Setting.BASIC_FILE);
        Map<String, String> advance = QueryUtils.loadData(Setting.ADVANCE_FILE);

        basicQueries = basic.entrySet().toArray(new Map.Entry[0]);
        advanceQueries = advance.entrySet().toArray(new Map.Entry[0]);

        queryCombobox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Map.Entry) {
                    setText((String) ((Map.Entry) value).getKey());
                }
                return this;
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI gui = new GUI();
                gui.setLocationRelativeTo(null);
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupData;
    private javax.swing.ButtonGroup btnGroupQuery;
    private javax.swing.JButton btnQuery;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTime;
    private javax.swing.JComboBox<Map.Entry<String,String>> queryCombobox;
    private javax.swing.JTextArea queryTextArea;
    private javax.swing.JRadioButton radio100;
    private javax.swing.JRadioButton radio1M;
    private javax.swing.JRadioButton radio5k;
    private javax.swing.JRadioButton radio60k;
    private javax.swing.JRadioButton radioAdvance;
    private javax.swing.JRadioButton radioBasic;
    private javax.swing.JScrollPane tableQuery;
    // End of variables declaration//GEN-END:variables
}
